### ISSUE TITLE
Testnet not land

### ISSUE THREAD

**Issue by Anita200810** [vision-consensus/vision-improvement-proposals#2]
please check this address why i don't get goken vs even though i'm taking tesnet

VZyW9J5PTmeVWoGvGJtkQHMH1KbyT9gcR4

**Comment by vchain007** [comment]
did u get testnet vs from faucet  ?

**Comment by darylccc** [comment]
An account can only get testnet vs from faucet once, u have already got it yesterday, so u cannot get it again

> please check this address why i don't get goken vs even though i'm taking tesnet
> 
> VZyW9J5PTmeVWoGvGJtkQHMH1KbyT9gcR4

**Comment by Anita200810** [comment]
try to check this transaction..how long i expected this to be mainnet and apparently i didn't get it 
Hash
f34e84ed2f8b890cb8a7332a82bd397b331871b587ccd2fd1e8017f36c036557

**Comment by darylccc** [comment]
This hash is testnet's transaction, and u have got 2000vs from this transaction. There are no restrictions in the early days of the testnet, so u can get multiple tested vs. Only testnet can get vs, mainnet can not get vs for testing. Now, the mainnet has been launched, u can get more info of the mainnet from these sites: https://www.visionscan.org, https://www.vtimes.app, https://www.v.network/

**Comment by darylccc** [comment]
Thanks for your contribution to vision-improvement-proposals, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
